networks:
  frontend:
    external: true
    name: reverse-proxy

services:
  linkstack:
    image: linkstackorg/linkstack:latest
    restart: ${RESTART}
    networks:
      - frontend
    volumes:
      - linkstack:/htdocs
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      # http
      - traefik.http.routers.linkstack.rule=Host(`${DOMAIN}`) || Host(`4679-62-178-62-138.ngrok-free.app`)
      - traefik.http.routers.linkstack.entrypoints=web

volumes:
  linkstack: