networks:
  frontend:
    external: true
    name: reverse-proxy

services:
  linkstack:
    image: linkstackorg/linkstack:latest
    restart: ${RESTART}
    networks:
      - frontend
    volumes:
      - linkstack:/htdocs
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      # http
      - traefik.http.routers.linkstack.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.linkstack.entrypoints=web

volumes:
  linkstack: